In [218]:
# This eda is imp for preparing date time column

In [220]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [222]:
df = pd.read_excel('flight_price.xlsx')
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [223]:
df.sample(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
3808,IndiGo,6/03/2019,Delhi,Cochin,DEL → HYD → MAA → COK,08:35,21:20,12h 45m,2 stops,No info,7682
3831,Vistara,15/05/2019,Banglore,Delhi,BLR → DEL,07:00,09:40,2h 40m,non-stop,No info,4668
6863,Air Asia,15/04/2019,Kolkata,Banglore,CCU → BLR,10:20,12:55,2h 35m,non-stop,No info,4409
7965,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,11:40,01:30 16 Jun,13h 50m,1 stop,No info,6795
7455,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → DEL → BLR,20:25,10:55 10 May,14h 30m,1 stop,In-flight meal not included,8066

In [224]:
df.shape

(10683, 11)

In [225]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [226]:
#Route has null values
#as per understanding a flight can not go from one place to another without taking
#route so lets drop the null value

In [227]:
df=df.dropna()

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  object
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  object
 6   Arrival_Time     10682 non-null  object
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
dtypes: int64(1), object(10)
memory usage: 1001.4+ KB

In [229]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [230]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [236]:
df['Date_of_Journey']

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10682, dtype: object

In [242]:
"Ajay/Kumar".split("/")

['Ajay', 'Kumar']

In [244]:
df["Day"] = df['Date_of_Journey'].str.split("/").str[0]
df["Month"] = df['Date_of_Journey'].str.split("/").str[1]
df["Year"] = df['Date_of_Journey'].str.split("/").str[2]

In [246]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Day                object
Month              object
Year               object
dtype: object

In [248]:
df["Day"] = df["Day"].astype(int)
df["Month"] = df["Month"].astype(int)
df["Year"] = df["Year"].astype(int)

In [250]:
df.drop("Date_of_Journey",axis =1,inplace = True)

In [252]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  Day              10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Year             10682 non-null  int64
dtypes: int64(4), object(9)
memory usage: 1.1+ MB

In [254]:
df.Arrival_Time.value_counts()

Arrival_Time
19:00           423
21:00           360
19:15           333
16:10           154
12:35           122
               ...
00:25 02 Jun      1
08:55 13 Mar      1
11:05 19 May      1
12:30 22 May      1
21:20 13 Mar      1
Name: count, Length: 1343, dtype: int64

In [256]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])
#we want 0th element only

In [258]:
df["Arrival_hour"] = df["Arrival_Time"].str.split(':').str[0]
df["Arrival_mins"] = df["Arrival_Time"].str.split(':').str[1]

In [260]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  Day              10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Year             10682 non-null  int64
 13  Arrival_hour     10682 non-null  object
 14  Arrival_mins     10682 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.3+ MB

In [262]:
df["Arrival_hour"]=df["Arrival_hour"].astype(int)
df["Arrival_mins"]=df["Arrival_mins"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  Day              10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Year             10682 non-null  int64
 13  Arrival_hour     10682 non-null  int64
 14  Arrival_mins     10682 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.3+ MB

In [264]:
df.drop('Arrival_Time',axis=1,inplace = True)

In [266]:
df['Dep_hour'] = df['Dep_Time'].apply(lambda x: x.split(":")[0])
df['Dep_mins'] = df['Dep_Time'].apply(lambda x: x.split(":")[1])
df['Dep_hour'] = df['Dep_hour'].astype(int)
df['Dep_mins'] = df['Dep_mins'].astype(int)
df.drop('Dep_Time',axis = 1,inplace = True)

In [268]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   Day              10682 non-null  int64
 9   Month            10682 non-null  int64
 10  Year             10682 non-null  int64
 11  Arrival_hour     10682 non-null  int64
 12  Arrival_mins     10682 non-null  int64
 13  Dep_hour         10682 non-null  int64
 14  Dep_mins         10682 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.3+ MB

In [270]:
df.Total_Stops

0        non-stop
1         2 stops
2         2 stops
3          1 stop
4          1 stop
           ...
10678    non-stop
10679    non-stop
10680    non-stop
10681    non-stop
10682     2 stops
Name: Total_Stops, Length: 10682, dtype: object

In [272]:
df.Total_Stops.value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [274]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4})

In [276]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  int64
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   Day              10682 non-null  int64
 9   Month            10682 non-null  int64
 10  Year             10682 non-null  int64
 11  Arrival_hour     10682 non-null  int64
 12  Arrival_mins     10682 non-null  int64
 13  Dep_hour         10682 non-null  int64
 14  Dep_mins         10682 non-null  int64
dtypes: int64(9), object(6)
memory usage: 1.3+ MB

In [278]:
#Route can be used in two ways
#to know source and destination>> which is already in the data
#as number of stops >> total stops is aleady there
#so route is a repeatative information

In [280]:
df.drop('Route',axis=1,inplace = True)

In [282]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Day              10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Arrival_hour     10682 non-null  int64
 11  Arrival_mins     10682 non-null  int64
 12  Dep_hour         10682 non-null  int64
 13  Dep_mins         10682 non-null  int64
dtypes: int64(9), object(5)
memory usage: 1.2+ MB

In [284]:
df.Duration

0        2h 50m
1        7h 25m
2           19h
3        5h 25m
4        4h 45m
          ...
10678    2h 30m
10679    2h 35m
10680        3h
10681    2h 40m
10682    8h 20m
Name: Duration, Length: 10682, dtype: object

In [286]:
df['duration_hour'] = df.Duration.str.split(' ').str[0].str.split('h').str[0]

In [288]:
df['duration_mins'] = df.Duration.str.split(' ').str[1].str.split('m').str[0]

In [290]:
df.drop('Duration',axis=1,inplace=True)

In [292]:
df.dtypes

Airline            object
Source             object
Destination        object
Total_Stops         int64
Additional_Info    object
Price               int64
Day                 int64
Month               int64
Year                int64
Arrival_hour        int64
Arrival_mins        int64
Dep_hour            int64
Dep_mins            int64
duration_hour      object
duration_mins      object
dtype: object

In [294]:
df.duration_hour.value_counts()

duration_hour
2     2402
1      621
3      501
7      487
5      481
9      445
12     428
8      424
13     407
11     365
10     355
6      340
14     337
15     268
23     264
26     241
16     234
4      222
22     218
24     197
21     196
25     186
27     179
20     162
18     141
19     134
17     129
28      94
29      65
30      49
38      34
37      17
33      13
32       9
34       8
35       7
36       7
31       6
47       2
42       2
39       2
5m       1
41       1
40       1
Name: count, dtype: int64

In [296]:
df["duration_hour"].replace('5m','5',inplace = True)

In [298]:
df["duration_hour"] = df.duration_hour.astype(int)

In [300]:
df['duration_mins'].fillna(0, inplace=True)

In [302]:
df.duration_mins

0        50
1        25
2         0
3        25
4        45
         ..
10678    30
10679    35
10680     0
10681    40
10682    20
Name: duration_mins, Length: 10682, dtype: object

In [304]:
df['duration_mins']=df['duration_mins'].astype(int)
df['duration_hour']=df['duration_hour'].astype(int)

In [306]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Total_Stops      10682 non-null  int64
 4   Additional_Info  10682 non-null  object
 5   Price            10682 non-null  int64
 6   Day              10682 non-null  int64
 7   Month            10682 non-null  int64
 8   Year             10682 non-null  int64
 9   Arrival_hour     10682 non-null  int64
 10  Arrival_mins     10682 non-null  int64
 11  Dep_hour         10682 non-null  int64
 12  Dep_mins         10682 non-null  int64
 13  duration_hour    10682 non-null  int64
 14  duration_mins    10682 non-null  int64
dtypes: int64(11), object(4)
memory usage: 1.3+ MB

In [308]:
df.Additional_Info.value_counts()

Additional_Info
No info                         8344
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [310]:
#either u drop additional info or keep it

In [312]:
df[['Airline','Source','Destination','Additional_Info']]

           Airline    Source Destination Additional_Info
0           IndiGo  Banglore   New Delhi         No info
1        Air India   Kolkata    Banglore         No info
2      Jet Airways     Delhi      Cochin         No info
3           IndiGo   Kolkata    Banglore         No info
4           IndiGo  Banglore   New Delhi         No info
...            ...       ...         ...             ...
10678     Air Asia   Kolkata    Banglore         No info
10679    Air India   Kolkata    Banglore         No info
10680  Jet Airways  Banglore       Delhi         No info
10681      Vistara  Banglore   New Delhi         No info
10682    Air India     Delhi      Cochin         No info

[10682 rows x 4 columns]

In [314]:
#All of the above categorical data is nominal data..so we wil be
#using one hot encoding

In [316]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [318]:
encoder

OneHotEncoder()

In [320]:
encoder.fit_transform(df[["Airline","Source","Destination","Additional_Info"]]).toarray()

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [322]:
encoder.get_feature_names_out()

array(['Airline_Air Asia', 'Airline_Air India', 'Airline_GoAir',
       'Airline_IndiGo', 'Airline_Jet Airways',
       'Airline_Jet Airways Business', 'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara',
       'Airline_Vistara Premium economy', 'Source_Banglore',
       'Source_Chennai', 'Source_Delhi', 'Source_Kolkata',
       'Source_Mumbai', 'Destination_Banglore', 'Destination_Cochin',
       'Destination_Delhi', 'Destination_Hyderabad',
       'Destination_Kolkata', 'Destination_New Delhi',
       'Additional_Info_1 Long layover',
       'Additional_Info_1 Short layover',
       'Additional_Info_2 Long layover', 'Additional_Info_Business class',
       'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype=object)

In [324]:
encoded_data = encoder.fit_transform(df[["Airline","Source","Destination","Additional_Info"]]).toarray()
encoded_data = pd.DataFrame(encoded_data,columns = encoder.get_feature_names_out())

In [326]:
df.drop(['Airline','Source','Destination','Additional_Info'],axis=1,inplace=True)

In [328]:
df

,Total_Stops,Price,Day,Month,Year,Arrival_hour,Arrival_mins,Dep_hour,Dep_mins,duration_hour,duration_mins
0,0,3897,24,3,2019,1,10,22,20,2,50
1,2,7662,1,5,2019,13,15,5,50,7,25
2,2,13882,9,6,2019,4,25,9,25,19,0
3,1,6218,12,5,2019,23,30,18,5,5,25
4,1,13302,1,3,2019,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,0,4107,9,4,2019,22,25,19,55,2,30
10679,0,4145,27,4,2019,23,20,20,45,2,35
10680,0,7229,27,4,2019,11,20,8,20,3,0
10681,0,12648,1,3,2019,14,10,11,30,2,40
10682,2,11753,9,5,2019,19,15,10,55,8,20

In [330]:
final_df = pd.concat([df,encoded_data],axis = 1)

In [332]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10683 entries, 0 to 9039
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10682 non-null  float64
 1   Price                                         10682 non-null  float64
 2   Day                                           10682 non-null  float64
 3   Month                                         10682 non-null  float64
 4   Year                                          10682 non-null  float64
 5   Arrival_hour                                  10682 non-null  float64
 6   Arrival_mins                                  10682 non-null  float64
 7   Dep_hour                                      10682 non-null  float64
 8   Dep_mins                                      10682 non-null  float64
 9   duration_hour                                 10682 non-null  float64
 10  duration_mins                                 10682 non-null  float64
 11  Airline_Air Asia                              10682 non-null  float64
 12  Airline_Air India                             10682 non-null  float64
 13  Airline_GoAir                                 10682 non-null  float64
 14  Airline_IndiGo                                10682 non-null  float64
 15  Airline_Jet Airways                           10682 non-null  float64
 16  Airline_Jet Airways Business                  10682 non-null  float64
 17  Airline_Multiple carriers                     10682 non-null  float64
 18  Airline_Multiple carriers Premium economy     10682 non-null  float64
 19  Airline_SpiceJet                              10682 non-null  float64
 20  Airline_Trujet                                10682 non-null  float64
 21  Airline_Vistara                               10682 non-null  float64
 22  Airline_Vistara Premium economy               10682 non-null  float64
 23  Source_Banglore                               10682 non-null  float64
 24  Source_Chennai                                10682 non-null  float64
 25  Source_Delhi                                  10682 non-null  float64
 26  Source_Kolkata                                10682 non-null  float64
 27  Source_Mumbai                                 10682 non-null  float64
 28  Destination_Banglore                          10682 non-null  float64
 29  Destination_Cochin                            10682 non-null  float64
 30  Destination_Delhi                             10682 non-null  float64
 31  Destination_Hyderabad                         10682 non-null  float64
 32  Destination_Kolkata                           10682 non-null  float64
 33  Destination_New Delhi                         10682 non-null  float64
 34  Additional_Info_1 Long layover                10682 non-null  float64
 35  Additional_Info_1 Short layover               10682 non-null  float64
 36  Additional_Info_2 Long layover                10682 non-null  float64
 37  Additional_Info_Business class                10682 non-null  float64
 38  Additional_Info_Change airports               10682 non-null  float64
 39  Additional_Info_In-flight meal not included   10682 non-null  float64
 40  Additional_Info_No Info                       10682 non-null  float64
 41  Additional_Info_No check-in baggage included  10682 non-null  float64
 42  Additional_Info_No info                       10682 non-null  float64
 43  Additional_Info_Red-eye flight                10682 non-null  float64
dtypes: float64(44)
memory usage: 3.7 MB

In [ ]:
#Internal homework--
#univariate analysis
#Bivariate analysis
#multivariate analysis
#considering price as target variable separate x and y
#scaling